### ISSUE TITLE
Added RX Multicast to tracking methods.

### ISSUE THREAD

**Issue by BADF00D** [BADF00D/DisposableFixer#142]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of DisposableFixer: 2.4.1 VS 2017
- [x] I have searched [open](https://github.com/BADF00D/DisposableFixer/issues) and [closed](https://github.com/BADF00D/DisposableFixer/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Static method System.Reactive.Linq.Observable.Multicast() tracks the given ReplaySubject and should be ignored during analysis.

### Source Code

```csharp

```

**Comment by BADF00D** [comment]
Part of release VS2017 2.4.2 and VS2019 3.2.2
