### ISSUE TITLE
Add System.Net.Http.StreamContext as tracking Disposable

### ISSUE THREAD

**Issue by BADF00D** [BADF00D/DisposableFixer#155]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of DisposableFixer: CURRENT
- [x] I have searched [open](https://github.com/BADF00D/DisposableFixer/issues) and [closed](https://github.com/BADF00D/DisposableFixer/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Source Code

```csharp
var ms = new MemoryStream();
ExcelWorkbookCreator.CreateWorkbookWithOneSheet(ms, _importData);
RequestContent = new StreamContent(ms);
```

### Screenshot

![image](https://user-images.githubusercontent.com/2852160/115821920-f52a9d80-a403-11eb-9278-b0f717194efe.png)
