### ISSUE TITLE
Added Annotation for custom tracking methods

### ISSUE THREAD

**Issue by BADF00D** [BADF00D/DisposableFixer#72]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of DisposableFixer: YOUR_VERSION
- [x] I have searched [open](https://github.com/BADF00D/DisposableFixer/issues) and [closed](https://github.com/BADF00D/DisposableFixer/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

In order to detect possible NullReferencesExceptions, JetBrains implemented some attributes within [JetBrains.Annotations](https://www.nuget.org/packages/JetBrains.Annotations/), so that everybody can mark their custom methods with attributes like CanBeNull. Something like that can be useful, too.

**IgnoreMethodDuringDisposeDetectionAttribute**
- ca be allied to classed and methods
- marks a method that should be ignored during dispose detection.

**IgnoreClassDuringDisposeDetectionAttribute**
- ca be allied to classed and methods
- Used for classes that implements IDisposable, but there is no need to dispose it,

**TrackingMethodAttribute**
- can be applied to methods
- defines that a method keeps track of IDisposable given via parameters 
- has optional parameter like: third parameter should be true

**CallsDisposeAttribute**
- can be applied to methods
- if this method was called, ```instance``` should be considered as disposed.
Example
```csharp
internal class Usage{
   public Usage(){
      var instance = new SomeSpecialClass() //this is not marked as undisposed, because Cleanup is called
      instance.Cleanup(); 
   }
}
internal class SomeSpecialClass : IDisposeable{
   [CallsDispose]
   public void Cleanup(){
      
   }
   public void Dispose(){
   }
}
```

**Comment by BADF00D** [comment]
Some new ideas
| Command | Description |
| --- | --- |
| git status | List all new or modified files |
| git diff | Show file differences that haven't been staged |

**Comment by BADF00D** [comment]
We need an additional attribute to mark an setter as Safe during ObjectInitialization. E.g.

```csharp
using System.Net;
using System.Net.Http;

namespace SomeNamespace
{
    internal class HttpResponseMessageSpec
    {
        public HttpResponseMessage CreateResponse1()
        {
            var msg = new HttpResponseMessage(HttpStatusCode.Accepted)
            {
                /* This should not yield an error because this is initialization and we Content if null after ctor was called. */
                Content = new StringContent("some content")
            };
            
            return msg;
        }
    }
}
```

There should be a Attribute that marks Content in order to signal, that Content is Null after ctor of HttpResponseMessage was called. Therefore the first set to Content with an IDisposable is allowed, 
We can modify TrackedSet. It can have a mode Always or OneTime

**Comment by BADF00D** [comment]
When DisposeCallAttribute is put on an interface method, the implementations and overrides should be treated as dispose calls as well

**Comment by BADF00D** [comment]
Checkout this https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/attributes/
